In [172]:
import numpy as np
A = np.array([[2., -1., -2.], [4., 2., 0.], [0., -2., -1.]])
B = np.array([[-1.], [6.],[-3.]])
A_extins = np.concatenate((A, B), axis=1)

In [173]:
def metoda_gaus(A, n):
    for k in range (0,n-1):
        for l in range(k + 1, n):
            raport = A[l,k]/A[k,k]
            A[l] = A[l] - raport * A[k] 

In [174]:
metoda_gaus(A_extins,3)

In [175]:
print(A_extins)

[[ 2. -1. -2. -1.]
 [ 0.  4.  4.  8.]
 [ 0.  0.  1.  1.]]


In [176]:
C = A_extins[:,-1]
U = A_extins[:,:-1]
print(U)

[[ 2. -1. -2.]
 [ 0.  4.  4.]
 [ 0.  0.  1.]]


In [177]:
x =np.array([[0.], [0.],[0.]])
def sis_triunghiular_superior(U,C,n):
    for k in range (n-1,-1, -1):
        suma = 0
        for j in range (k+1, n):
            suma += U[k][j] * x[j]
        x[k] = (C[k] - suma) / U[k][k]
    return x

In [178]:
n = 3
x = sis_triunghiular_superior(U,C,n)
print(x)

[[1.]
 [1.]
 [1.]]


In [167]:
np.dot(U,x)

array([[-1.],
       [ 8.],
       [ 1.]])