In [1]:
#pb1

import numpy as np

def gauss_pivotare_totala(A, b):
    
    n = A.shape[0]

    # Formez matricea extinsa a sistemului
    M = np.concatenate((A, b), axis=1)
    
    #creez un vector de indici in care pun numere consecutive de la 0 la n-1 (0,1,2....)
    indices = np.arange(0, n)

    for k in range(n - 1):
        p = k
        m = k
        # determinam cel mai mare nr in modul de la linia/coloana k la final
        for i in range(k,n):
            for j in range(k,n):
                if abs(M[i, j]) > abs(M[p, m]):
                    p = i
                    m = j
        
        # inteschimb linia k si linia p
        if p != k:
            M[[p, k]] = M[[k, p]]

        # inteschimb coloana k si linia m si am grja sa schimb si ordinea in vectorul indices
        if m != k:
            M[:, [m, k]] = M[:, [k, m]]
            indices[[m,k]] = indices[[k,m]]
            
        # creez zero-uri cum faceam si la gaus fara pivotare
        for l in range(k + 1, n):
            raport = M[l,k]/M[k,k]
            M[l] = M[l] - raport * M[k] 
            
    return M,indices
    

def sis_triunghiular_superior(U,C):
    
    #functia identica cu cea de la gaus fara pivotare care rezolva un sistem triunghiular superior
    n = U.shape[0]
    x = np.zeros(N)
    for k in range (n-1,-1, -1):
        suma = 0
        for j in range (k+1, n):
            suma += U[k][j] * x[j]
        x[k] = (C[k] - suma) / U[k][k]
    return x

A = np.array([[0., 2., -1., 4.], [5., 9., 8., -10.], [-4., -3., 4., 9.], [3., 9., -10., -7.]])
b = np.array([[27.], [31.],[50.],[-47.]]) 

# verific mai intai daca determinantul este diferit de 0 ca sa pot sa vad daca exista o solutie unica
det = np.linalg.det(A)
if abs(det) >= 1e-8:  
    print('Determinantul este ', det, 'deci sistemul admite o solutie unica')
    # in acest caz aplic gaus cu pivotare totala si aflu solutiile sistemului
    M, indexes = gauss_pivotare_totala(A, b) 

    N = A.shape[0]
    U = M[:,:N]
    C = M[:,N]

    x = sis_triunghiular_superior(U, C)
    x = x[indexes]
    print('Rezultatul este:')
    print(x)
    print('Verificare A * x =', np.dot(A,x))
    print('b = ', b)
    
else:
    # in acest caz nu am cum sa aflu x deoarele sistemul nu admite o solutie unica
    print('Determinantul este ', det, 'deci sistemul nu admite o solutie unica')

Determinantul este  1987.0000000000005 deci sistemul admite o solutie unica
Rezultatul este:
[3. 4. 5. 6.]
Verificare A * x = [ 27.  31.  50. -47.]
b =  [[ 27.]
 [ 31.]
 [ 50.]
 [-47.]]


In [2]:
#pb2

def gaussian_elimination(A):
    m = A.shape[0]
    # formez matricea identitate Im
    I = np.identity(m)
    
    # concatenez pe A cu I
    A_extins = np.concatenate((A, I), axis=1)
    j = 0
    for i in range(m-1):
        # caut un pivot nenul
        pivot = A_extins[i][j]
        if pivot == 0:
            found = False
            # daca pivotul este nul caut pe liniile urmatoare pana gasesc unul nenul
            for k in range(i+1,m):
                if A_extins[k][j] != 0:
                    # inversez linia k cu linia i atunci cand gasesc un pivot nenul
                    A_extins[[k, i]] = A_extins[[i, k]]
                    found = True 
                    break
            if found == False:
                raise Exception("Matricea nu poate fi inversata")
            else:
                pivot = A_extins[i][j]
                
        # creez zero-uri sub pivot in matricea din dreapta (primele 4 coloane devin superior triunghiulare)        
        for k in range(i+1, m):
            raport = A_extins[k][j] / pivot
            A_extins[k] = A_extins[k] - raport * A_extins[i]
        j += 1
        
        
    #Generam zero-uri deasupra pivotului si obtinem o matricea cu elemente nenule doar pe diagonala principala
    j = m-1
    for i in range(m-1,0,-1):
        pivot = A_extins[i][j]
        for k in range(i-1,-1,-1):
            raport = A_extins[k][j] / pivot
            A_extins[k] = A_extins[k] - raport *A_extins[i]
        j -= 1
        
    # impartim fiecare linie a matricei cu valoarea elementului de pe diag principala(singurul element nenul din matr din stanga)
    # astfel in stanga voi obtine matricea identitate
    for i in range(m):
        A_extins[i] /= A_extins[i][i]
        
    # A_extins va avea in stanga I4 si in dreapta matricea inversata asa ca returnam inversa, adica coloanele de la m la sfarsit
    return A_extins[:,m:]


B = np.array([[0., 1., -6., -3.], [-9., -2., -8., -2.], [-3., -8., 2., -6.], [-1., -8., 4., 3.]])

# verific mai intai daca determinantul este diferit de 0 ca sa pot sa vad daca matricea este inversabila
det = np.linalg.det(B)
if abs(det) >= 1e-8:  
    print('Determinantul este ', det, 'deci matricea este inversabila')
    B_inv = gaussian_elimination(B)
    print('Inversa matricii B este: ', B_inv)
    print('Verificare: B * B_inv = ', np.round(np.dot(B, B_inv)))
else:
    # in acest caz nu am cum sa aflu inversa matricei intrucat determinatul este 0
    print('Determinantul este ', det, 'deci matricea nu este inversabila')
        

Determinantul este  -3158.0 deci matricea este inversabila
Inversa matricii B este:  [[ 0.19126029 -0.11209626 -0.02153262  0.07346422]
 [-0.11716276  0.01899937 -0.01329956 -0.13109563]
 [-0.18556048 -0.01044965  0.05731476 -0.0778974 ]
 [-0.00126662  0.02723243 -0.1190627   0.11209626]]
Verificare: B * B_inv =  [[ 1.  0.  0.  0.]
 [-0.  1.  0. -0.]
 [-0. -0.  1. -0.]
 [ 0. -0. -0.  1.]]


In [3]:
#pb3

def LU_pivotare_partiala(A,b):
    
    N = A.shape[0]
    # matricea identitate
    P = np.eye(N)
    # matrice cu zero-uri
    L = np.zeros((N, N))
    # copia lui A
    U = np.copy(A)

    for k in range(N - 1):
        
        # Gasesc indicele elementului avand valoarea absoluta maxima
        index = k + np.argmax(np.abs(U[k:, k]))

        # Interschimb liniile p si k in U, L si P
        U[[k, index]] = U[[index, k]]
        L[[k, index]] = L[[index, k]]
        P[[k, index]] = P[[index, k]]

        # Selectez coloana pe care lucrez
        raport = U[k + 1:, k]

        # Determin raportul pentru fiecare rand
        raport = raport / U[k, k]

        # Actualizez matricea inferior triunghiulara
        L[k + 1:, k] = raport

        # Selectez randul pe care vreau sa-l actualizez
        rand = U[k, :]

        # Inmultesc fiecare raport cu primul rand
        diferenta = np.outer(raport, rand)

        # Actualizez matricea superior triunghiulara
        U[k + 1:, :] -= diferenta
    
    # adaug lui L matricea identitate
    L += np.eye(N)

    print("L = ", L)
    print("U = ", U)
    print("L @ U = ", L @ U)
    print("P @ A = ", P @ A)
    
    # Permut numerele din vector
    b = P @ b

    y = np.zeros(N)

    # Merg de la prima linie în jos si rezolv pe rand ecuațiile prin substitutie
    for i in range(0, N):
        coefs = L[i, :i + 1]
        values = y[:i + 1]
        y[i] = (b[i] - coefs @ values) / L[i, i]

    print("Obtin y = ", y)

    x = np.zeros(N)

    # Merg de la ultima linie în sus si rezolv pe rand ecuațiile prin substituție
    for i in range(N - 1, -1, -1):
        coefs = U[i, i + 1:]
        values = x[i + 1:]
        x[i] = (y[i] - coefs @ values) / U[i, i]

    print("Obțin x = ", x)
    print("Verificare: A @ x = ", A @ x)
    
A = np.array([[0., -3., -6., 2.], [6., 0., 6., -2.], [1., -4., 8., 1.], [-4., 0., -9., -9.]])
b = np.array([[-30.], [36.],[33.],[-111.]]) 

# verific mai intai daca determinantul este diferit de 0 ca sa pot sa vad daca sistemul admite solutie unica
det = np.linalg.det(A)
if abs(det) >= 1e-8:  
    print('Determinantul este ', det, 'deci sistemul admite solutie unica')
    LU_pivotare_partiala(A,b)
else:
    # in acest caz nu am cum sa aflu x deoarele sistemul nu admite o solutie unica
    print('Determinantul este ', det, 'deci sistemul nu admite solutie unica')

Determinantul este  -2909.999999999999 deci sistemul admite solutie unica
L =  [[ 1.          0.          0.          0.        ]
 [ 0.16666667  1.          0.          0.        ]
 [ 0.          0.75        1.          0.        ]
 [-0.66666667  0.          0.44444444  1.        ]]
U =  [[  6.           0.           6.          -2.        ]
 [  0.          -4.           7.           1.33333333]
 [  0.           0.         -11.25         1.        ]
 [  0.           0.           0.         -10.77777778]]
L @ U =  [[ 6.  0.  6. -2.]
 [ 1. -4.  8.  1.]
 [ 0. -3. -6.  2.]
 [-4.  0. -9. -9.]]
P @ A =  [[ 6.  0.  6. -2.]
 [ 1. -4.  8.  1.]
 [ 0. -3. -6.  2.]
 [-4.  0. -9. -9.]]
Obtin y =  [ 36.          27.         -50.25       -64.66666667]
Obțin x =  [3. 4. 5. 6.]
Verificare: A @ x =  [ -30.   36.   33. -111.]


In [4]:
#pb4

from numpy import sqrt

def DescCholesky(A):
    # verific daca pot extrage radical
    if A[0, 0] <= 0:
        print("A nu este pozitiv definita!")
        
    n = A.shape[0]
    
    # matrice cu zero-uri   
    L = np.zeros((n,n))
  
    #Pasul 1
    L[0, 0] = sqrt(A[0, 0])
    # elementele de pe prima coloana vor fi egale cu raportul dintre elem initial din A si L[0][0]
    for i in range (1, n):
        L[i, 0] = A[i, 0] / L[0, 0]
  
    #Pasul 2
    # calculez de la coloana 2 la ultima coloana 
    for k in range (1, n):
        suma = 0
        # calculez suma patratelor elementelor liniiei k si coloanele pana la k
        for s in range (0, k):
            suma += L[k, s] * L[k,s]
        
        alpha = A[k, k] - suma
        # verific daca alpha este >0 pentru a putea extrage radical
        if alpha <= 0:
            print("A nu este pozitiv definita!")
        
        L[k, k] = sqrt(alpha)
        # parcurg liniile de dupa k
        for i in range (k + 1, n):
            suma = 0;
            for s in range (0, k):
                suma += L[i, s] * L[k, s]
            L[i, k] = 1 / L[k, k] * (A[i, k] - suma)
            
    return L
    
C = np.array([[36., 18., 30., 48.], [18., 13., 5., 26.], [30., 5., 75., 0.], [48., 26., 0., 178.]])
L = DescCholesky(C)
print(L)

[[ 6.  0.  0.  0.]
 [ 3.  2.  0.  0.]
 [ 5. -5.  5.  0.]
 [ 8.  1. -7.  8.]]
