#Tema 2

## 1. Inversa unei matrici

In [1]:
# Vom folosi metoda Gaus pentru a calcula inversa unei matrici

import numpy as np

def gaus_pivotare_partiala(m):
    # nr de linii
    n = m.shape[0]
    #M = M.copy()

    for k in range(n - 1):
        pivot = m[k, k]
        
        # Ma asigur ca fiecare rand incepe cu 1
        if pivot != 1:
            m[k] *= 1/pivot

        # Determin raportul pentru fiecare rand
        ratie = m[k + 1:, k] / m[k, k]

        linie = m[k, :]

        # Inmultesc fiecare raport cu primul rand 
        diferenta = np.outer(ratie, linie)

        # Actualizez matricea
        m[k + 1:, :] -= diferenta

    return m


def inversa_matrice(a):
    # nr de linii
    n = a.shape[0]
    
    # adaug la matricea a, matricea identitate
    m = np.hstack((a, np.eye(3)))
    
    # aplic gaus cu pivotare partiala
    u = gaus_pivotare_partiala(m)

    # formez I3 in primele 3 coloane
    for i in range(1, n):
        for j in range(i):
            ratie = u[j, i] / u[i, i]
            u[j] -= ratie * u[i, :]
    
    # acum ca partea din stanga este chiar I3, partea din dreapta va fi chiar inversa matricei
    return u[:, n:]

In [2]:
m = np.array([[1, -1, 1], [2, 0, 3], [1, 1, -2]], dtype=np.float)

inversa = inversa_matrice(m)

print(inversa)

[[ 0.375  0.125  0.375]
 [-0.875  0.375  0.125]
 [ 1.    -1.     1.   ]]


##2. Lema Substitutiei

In [11]:
m = np.array([[1, 0, 0],[0, 2, 0],[0, 0, 1]])

# nr linii matrice
n = m.shape[0]

# calculez inversa matricei
inversa = inversa_matrice(m)

C = np.array([2, 1, 1], dtype=np.float)

# aleg un k intre 1 si n
k = 1

# calculez m_tilda ca fiind m, dar avand coloana k cu C
m_tilda = m.copy()
m_tilda[:, k] = C

# calculez y ca fiind inversa*C
y = inversa @ C

# calculez eta
eta = -y / y[k]
eta[k] = 1 / y[k]

# calculez E_k ca fiind I3, avand coloana k inlocuita cu eta
E_k = np.eye(n)
E_k[:, k] = eta

m_tilda_inv = E_k @ inversa

print("Inversa lui m_tilda este:")
print(m_tilda_inv)

Inversa lui m_tilda este:
[[ 1. -2.  0.]
 [ 0.  1.  0.]
 [ 0. -1.  1.]]
